version: '3.7'
services:
  mysql:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: mysql
    restart: always
    ports:
      - 23306.3306
    environment:
      MYSQL_ROOT_PASSWORD: "PedroAtos2022"      
    volumes: 
      - ./schemas:/var/lib/mysql:rw
    networks:
      mysql_network:
        aliases: 
         - mysql_host
volumes:
  schemas: {}
networks:
  mysql_network:
    name: mysql_net
    driver: bridge

